name: Newman Tests by Postman.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '0 7 * * MON-FRI'

  workflow_dispatch:
permissions: write-all

jobs:
  automated-api-integracao:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 20
      - run: npm install -g newman &&
             npm install -g allure-commandline --save-dev &&
             npm install -g newman-reporter-allure 

      - name: Step 2 - Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
            newman run DEV Copy.postman_collection.json -r allure -e ORBITAL_SANDBOX.postman_collection.json

      - name: mostra as pastas
        run: dir
      - name:  Step 3 - Collect Allure files and generate allure-report folder
        run: |
          allure generate ./allure-results -o allure-report/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: main
         publish_dir: ./build
         destination_dir: /
