name: Newman Tests by Postman.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '0 7 * * MON-FRI'

  workflow_dispatch:
permissions: write-all

jobs:
  automated-api-integracao:
    runs-on: windows-latest
    steps:
      # 1 -Step- Install Dependencies.
      - uses: actions/checkout@v3
      - uses: actions/setup-note@v3
        with:
            node-version: 20
      - run: npm install -g newman |
             npm install -g allure-commandline --save-dev |
             npm install -g newman-reporter-allure 

      # 2 -Step- Run the Postman Collection.
      - name: Step 2 - Run POSTMAN collecton
        if: always()
        continue-on-error: true
        run: |
            newman run DEV Copy.postman_collection.json -r allure

      - name: mostra as pastas
        run: dir
      - name:  Step 3 - Collect Allure files and generate allure-report folder
        run: |
          allure generate ./allure-results -o allure-report/
      - name: Step 4 - Publishing Allure artifacts to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}      
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: allure-report
          destination_dir: allure-report
